---
name: t2

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-action2:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs some action
      - name: Run some action 2
        run: ls -la
